name: http_middleware
description: An Http client that uses middleware to handle requests.
version: 1.0.0
repository: https://github.com/AndreyKedo/http_middleware

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  http: ^1.2.1
  meta: any

dev_dependencies:
  lints: any
  test: ^1.25.2
