name: rest_client
description: A simple lightweight REST client.
version: 1.0.0

publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  http: ^1.2.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
