name: http_middleware_client
description: An wrapper around package [http](https://pub.dev/packages/http) HTTP client that supports middleware for processing requests and responses.
version: 1.0.0+1
repository: https://github.com/AndreyKedo/http_middleware

topics:
  - http
  - client
  - middleware
  - network

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  http: ^1.5.0
  meta: ^1.15.0

dev_dependencies:
  lints: any
  test: ^1.25.2
